### PR TITLE
Updated RA4 YDH Resources for new test

### PR DESCRIPTION
**Pull request by Fdawgs**
- Updated all resources to be in line with what they currently look like in YDH's system.
- Updated Encounter resources for patient 5 to match what was agreed with MH.

### CODE REVIEW

**Review by Dunmail — CHANGES_REQUESTED** [review]
Patient.identifier uses, the system `https://fhir.nhs.uk/Id/local-patient-identifier`, an unsafe anti-pattern! 

The problem is that there is no way to differentiate patients with the same identifier (_e.g._ 9999999991) that has been allocated by different organisations. Even worse, where the same identifier has been allocated by different organisations, using the **same system** means that we are asserting that this is the **same patient**. This has been reported to NHS Digital and INTEROPen for resolution.

Recommend that you allocate identifiers from your own namespace (_e.g._ `https://fhir.ydh.nhs.uk/Id/local-patient-identifier`

**Review by Dunmail — COMMENTED** [review]
I would strongly recommend **not** using NHS number (a business identifier for the individual) as the resource id (a logical identifier for the resource at your endpoint) (_e.g._`https://sider.ydh.nhs.uk/3_0_1/Patient/9449307393`).

The problem is that across the NHS many organisations will have different Patient resources relating to the same individual. If several organisations use NHS number for the resource then we will have multiple Patient resources where id = 9449307393. If the id is the same, a consumer may regard them as **different versions of the same resource** rather than **different resources about the same individual**.

I suggest using a guid for the logical identifier. If there isn't a natural identifier already available, then you could salt and hash the NHS number (e.g. generate a guid using the MD5 hash of (ydh.nhs.uk|9449307393)

**Review by Dunmail — COMMENTED** [review]
Encounter.type is currently carrying 2 different classes of information (specialty and type). I'll have a think about this!

**Review by Dunmail — APPROVED** [review]

**Review by Dunmail — CHANGES_REQUESTED** [review]
'MedicationStatement.code.text' should be 'MedicationStatement.dosage.text'

**Comment by Fdawgs** [comment]
> 
> 
> Encounter.type is currently carrying 2 different classes of information (specialty and type). I'll have a think about this!

Thanks Dunmail, couldn't see anywhere else within the spec/profile to declare the specialty.

**Comment by Dunmail** [comment]
Got it - looks like we can use `Encounter.class` for the type of encounter (inpatient | outpatient | emergency etc):
http://hl7.org/fhir/stu3/encounter-definitions.html#Encounter.class

We can then use `Encounter.type` for the specialty.

And it looks like there is an NHS standard set of codes for specialty. At the moment it is within a Digital Child Health resource, but I bet this will become a generic list: https://fhir.nhs.uk/STU3/CodeSystem/DCH-Specialty-1

**Pull request merged**
